# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 双轮行博客
email: 2237993760@qq.com
description: > # this means to ignore newlines until "baseurl:"
    一个人，双轮行！  
baseurl: "" # the subpath of your site, e.g. /blog
url: "twolun.github.io" # the base hostname & protocol for your site
twitter_username: twolun
github_username:  twolun

# Build settings
markdown: kramdown
