markdown: kramdown
kramdown:
  extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
highlighter: rouge
redcarpet:
  extensions:
    - fenced_code_blocks
    - no_intra_emphasis
    - strikethrough
    - autolink
    - tables
safe: false
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
permalink: /posts/:title.html
exclude:
  - README.md

name: 双轮行
url: twolun.github.com
baseurl: 
desc: 越努力 越幸运

custom:
    category:
        knowledge: knowledge
        database: database
        technique: technique
        others: others

    categories:
      - name:  knowledge
        title: 知道相关

      - name:  database
        title: database

      - name: technique
        title: 技术探索

      - name: others
        title: 其它

meta:
    author:
        name: 双轮行
        email: 2237993760@qq.com
        disqus: wwsun                               # Disqus缩略标识
        gcse: 017273734144320215856:r-n1xry8woo     # Google自定义搜索标识ID
        github: https://github.com/twolun                               # GitHub账号
        gravatar: 48b4b2d677d28780288ab93737230019  # Gravatar头像标识
        image: /img/site/logo.jpeg  # 头像URL

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址

